language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - FRAMEWORK_VERSION="4.1.*" SKELETON_VERSION="4.1.*"
  - FRAMEWORK_VERSION="4.2.*" SKELETON_VERSION="4.2.*"
  - FRAMEWORK_VERSION="4.3.*@dev" SKELETON_VERSION="dev-develop@dev"

before_install:
  - composer require illuminate/database:${FRAMEWORK_VERSION} --no-update
  - composer require laravel/laravel:${SKELETON_VERSION} --dev --no-update

install: composer install --dev --prefer-dist

script: phpunit
