language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - LV="4.1.*"
  - LV="4.2.*"
  - LV="5.0.*"

before_install:
  - composer require illuminate/database:${LV} --no-update

install:
  - composer install --dev --no-interaction

script:
  - phpunit

sudo: false
