language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - LV="4.1.*"
  - LV="4.2.*"
  - LV="5.1.*"
  - LV="5.5.*"
  - LV="5.6.*"

before_install:
  - composer require illuminate/database:${LV} --no-update

install:
  - composer install --dev --no-interaction

script:
  - phpunit

sudo: false
